<?php $site = 'Кабинет'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">


            <!-- Показать определенную nav в зависимости от того создаем ли мы или изменяем уже созданный тип проекта -->
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/profile">Личный кабинет</a></li>
                    <li class="breadcrumb-item active">Новый тип проекта</li>
                </ol>
            </nav>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Изменить тип проекта</li>
                </ol>
            </nav>


            <div class="card">
                <div class="card-body">

                    <!-- choose one -->
                    <h4 class="card-title text-center"><strong>Создание типа проекта</strong></h4>
                    <h4 class="card-title text-center"><strong>Изменить существующий тип проекта</strong></h4>


                    <p class="text-left mb-1 red-text">* - обязательно для заполнения</p>
                    <form enctype="multipart/form-data" class="md-form mt-1 mb-1" action="" method="post">
                        <p class="text-left mt-3 mb-1"><strong>1. Название типа проекта</strong><span class="red-text"> *</span></p>
                        <div class="md-form mt-3">

                            <!-- Пример того как можно добавить название заранее -->
                            <input type="text" name="title" id="ProjectName" class="form-control" required value="Дизайн">
                            <label for="ProjectName">Название типа</label>
                        </div>
                        <p class="text-left mt-3 mb-1"><strong>2. Лидер проекта</strong><span class="red-text"> *</span></p>
                        <select name="leader" class="browser-default custom-select mt-3" required>
                            <option value="" disabled selected>Выберите лидера проекта</option>
                            <?php foreach($leaders as $leader)
                            {
                                echo '<option value="'.$leader['id'].'">'.$leader['surname'].' '.$leader['name'].' '.$leader['patronymic'].'</option>';
                            }
                                ?>
                        </select>
                        <p class="text-left mt-3 mb-1"><strong>3. Описание типа проекта</strong></p>
                        <div class="md-form mt-3">

                            <!-- Пример того как можно добавить текст заранее -->
                            <textarea type="text" name="description" id="ProjectDescription" class="form-control md-textarea" rows="3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</textarea>
                            <label for="ProjectDescription">Описание типа</label>
                        </div>
                        <button class="btn btn-info btn-block my-4" name="create" type="submit">Создать тип проекта</button>
                    </form>
                </div>
            </div>
        </div>
  </main>
  <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
</body>
</html>