<?php $site = 'Кабинет'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/profile">Личный кабинет</a></li>
                    <li class="breadcrumb-item active">Просмотр и изменение учетных записей</li>
                </ol>
            </nav>
            <div class="table-responsive">
                <table id="tablePreview" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>login</th>
                            <th>avatar</th>
                            <th>type</th>
                            <th>position</th>
                            <th>project_type</th>
                            <th>name</th>
                            <th>surname</th>
                            <th>patronymic</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody class="white">
                    <?php foreach($accs as $acc)
                    {
                        echo '<tr>
                        <th>'.$acc['id'].'</th>
                        <td>'.$acc['login'].'</td>
                        <td>'.$acc['pic'].'</td>
                        <td>'.$acc['type'].'</td>
                        <td>'.$acc['position'].'</td>
                        <td>'.$acc['project_type'].'</td>
                        <td>'.$acc['name'].'</td>
                        <td>'.$acc['surname'].'</td>
                        <td>'.$acc['patronymic'].'</td>
                        <td><button type="button" class="btn btn-link p-0">Редактировать</button></td>
                        <td><button type="button" class="btn btn-link p-0">Удалить</button></td>
                        </tr>';
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
  </main>
  <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>