<?php $site = 'Добавить Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/profile">Личный кабинет</a></li>
                    <li class="breadcrumb-item active">Создание проекта</li>
                </ol>
            </nav>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center"><strong>Создание проекта</strong></h4>
                    <p class="text-left mb-1 red-text">* - обязательно для заполнения</p>
                    <form enctype="multipart/form-data" class="md-form mt-1 mb-1" action="" method="post">
                        <p class="text-left mt-3 mb-1"><strong>1. Название проекта</strong><span class="red-text"> *</span></p>
                        <div class="md-form mt-3">
                            <input type="text" name="title" id="materialSubscriptionFormPasswords" value="<?php if ($edit == 1) echo $project['title']; ?>" class="form-control" required>
                            <label for="materialSubscriptionFormPasswords">Название</label>
                        </div>
                        <p class="text-left mt-3 mb-1"><strong>2. Куратор</strong><span class="red-text"> *</span></p>
                        <select class="browser-default custom-select" name="curator" id="curator" required>
                            <option value="" disabled <?php if ($edit == 0) echo 'selected'; ?>>Выберите куратора</option>
                            <?php foreach($curators as $curator) {
                                echo '<option ';
                                if ($edit && $curator['id'] == $project['curator_id'])
                                    echo 'selected';
                                echo ' value="'.$curator['id'].'/'.$curator['surname'].' '.$curator['name'].' '.$curator['patronymic'].'">'.$curator['surname'].' '.$curator['name'].' '.$curator['patronymic'].'</option>';
                            }
                            ?>
                        </select>
                        <p class="text-left mt-3 mb-1"><strong>3. Описание проекта</strong></p>
                        <div class="md-form mt-3">
                            <textarea type="text" name="description" id="materialContactFormMessage" class="form-control md-textarea" value="<?php if ($edit == 1) echo $project['description']; ?>" rows="3"></textarea>
                            <label for="materialContactFormMessage">Описание</label>
                        </div>
                        <p class="text-left mb-1"><strong>4. Количество команд на проекте</strong><span class="red-text"> *</span></p>
                        <select class="browser-default custom-select mb-2" name="teams" required>
                            <option value="" <?php if ($edit == 0) echo 'selected'; ?>>Не выбрано</option>
                            <option value="1" <?php if ($edit == 1 && (explode('/', $project['team/students']))[0] == 1) echo 'selected'; ?>>1</option>
                            <option value="2" <?php if ($edit == 1 && (explode('/', $project['team/students']))[0] == 2) echo 'selected'; ?>>2</option>
                            <option value="3" <?php if ($edit == 1 && (explode('/', $project['team/students']))[0] == 3) echo 'selected'; ?>>3</option>
                        </select>
                        <p class="text-left mb-1"><strong>5. Количество членов команды</strong><span class="red-text"> *</span></p>
                        <select class="browser-default custom-select" name="size" required>
                            <option value="" <?php if ($edit == 0) echo 'selected'; ?>>>Не выбрано</option>
                            <option value="1" <?php if ($edit == 1 && (explode('/', $project['team/students']))[1] == 1) echo 'selected'; ?>>1</option>
                            <option value="2" <?php if ($edit == 1 && (explode('/', $project['team/students']))[1] == 2) echo 'selected'; ?>>2</option>
                            <option value="3" <?php if ($edit == 1 && (explode('/', $project['team/students']))[1] == 3) echo 'selected'; ?>>3</option>
                            <option value="4" <?php if ($edit == 1 && (explode('/', $project['team/students']))[1] == 4) echo 'selected'; ?>>4</option>
                            <option value="5" <?php if ($edit == 1 && (explode('/', $project['team/students']))[1] == 5) echo 'selected'; ?>>5</option>
                        </select>
                        <?php if ($edit == 0): ?>
                        <button class="btn btn-info btn-block my-4" name="create" type="submit">Создать проект</button>
                        <?php else: ?>
                        <button class="btn btn-info btn-block my-4" name="save" type="submit">Сохранить</button>
                        <?php endif; ?>
                    </form>
                </div>
            </div>
        </div>
  </main>
  <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
</body>
</html>