<?php $site = 'Добавить Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>

<!-- Custom styles -->
<link href="/template/css/main.css" rel="stylesheet">
  <link href="/template/css/project.css" rel="stylesheet">
  </head>
  <body class="d-flex flex-column h-100">

<header>
    <nav class="navbar navbar-expand-lg navbar-dark elegant-color-dark">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-555"
          aria-controls="navbarSupportedContent-555" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <!-- <?php if (isset($_SESSION['user'])): ?> -->
                <div class="dropdown user-dropdown align-self-end">
                    <button class="btn btn-primary dropdown-toggle btn-blue btn-rounded" type="button" id="dropdownMenu1" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><?php echo ($_SESSION['user']['name'].' '.$_SESSION['user']['surname']) ?></button>

                    <div class="dropdown-menu dropdown-primary dropdown-user">
                        <a class="dropdown-item" href="#"><i class="fal fa-user-circle fa-lg" aria-hidden="true" style="padding-right: 8px;"></i>Личный кабинет</a>
                        <a class="dropdown-item" href="#"><i class="far fa-calendar fa-lg" aria-hidden="true" style="padding-right: 8px;"></i>График</a>
                        <a class="dropdown-item" href="#"><i class="fas fa-file-alt fa-lg" aria-hidden="true" style="padding-right: 8px;"></i>Мои проекты</a>
                        <a class="dropdown-item" href="/logout"><i class="fas fa-power-off fa-lg" aria-hidden="true" style="padding-right: 8px;"></i>Выйти</a>
                    </div>
                </div>
            <!-- <?php else: ?> -->
            <a class="btn btn-primary btn-blue btn-rounded btn-login" href="/login" style="align-self: flex-end;" type="button">Войти</a>
            <!-- <?php endif; ?> -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent-555">
          <a class="navbar-brand mr-5" href="/projects">Проекты МосПолитеха</a>
          <ul class="navbar-nav mt-lg-0">
          <li class="nav-item dropdown mr-4 mega-dropdown active">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink2" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">Проекты
                    </a>
                    <div class="dropdown-menu mega-menu v-2 z-depth-1 elegant-color px-3" aria-labelledby="navbarDropdownMenuLink2">
                            <div class="row">
                            <a class="nav-link mx-3" href="/projects">Все</a>
                    <a class="nav-link mx-3" href="/projects/transport">Транспорт</a>
                    <a class="nav-link mx-3" href="/projects/tech">Технология</a>
                    <a class="nav-link mx-3" href="/projects/him">Химбиотех</a>
                    <a class="nav-link mx-3" href="/projects/energ">Энергетика</a>
                    <a class="nav-link mx-3" href="/projects/design">Дизайн</a>
                    <a class="nav-link mx-3" href="/projects/social">Социальные Технологии</a>
                    <a class="nav-link mx-3" href="/projects/initiativ">Инициативные проекты</a>
                        </div>
                        </div>
                    </li>
                    <li class="nav-item mr-4">
                        <a class="nav-link" href="/users">Участники</a>
                    </li>
                    <li class="nav-item mr-4">
                        <a class="nav-link" href="/teams">Команды</a>
                    </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main class="flex-fill">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/profile/projects">Мои Проекты</a></li>
                    <li class="breadcrumb-item active">Создание проекта</li>
                </ol>
            </nav>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title text-center"><strong>Создание проекта</strong></h4>
                    <p class="text-left mb-1 red-text">* - обязательно для заполнения</p>
                    <form enctype="multipart/form-data" class="md-form mt-1 mb-1" action="" method="post">
                        <p class="text-left mt-3 mb-1"><strong>1. Название проекта</strong><span class="red-text"> *</span></p>
                        <div class="md-form mt-3">
                            <input type="text" name="title" id="materialSubscriptionFormPasswords" class="form-control" required>
                            <label for="materialSubscriptionFormPasswords">Название</label>
                        </div>
                        <p class="text-left mb-1"><strong>2. Описание проекта</strong><span class="red-text"> *</span></p>
                        <div class="md-form mt-3">
                            <textarea type="text" name="description" id="materialContactFormMessage" class="form-control md-textarea" rows="3"></textarea>
                            <label for="materialContactFormMessage">Описание</label>
                        </div>

                        <p class="text-left mb-1"><strong>3. Количество команд на проекте</strong><span class="red-text"> *</span></p>
                        <select class="browser-default custom-select mb-2" name="size" required>
                            <option value="" selected>Не выбрано</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                        </select>
                        <p class="text-left mb-1"><strong>4. Количество членов команды</strong><span class="red-text"> *</span></p>
                        <select class="browser-default custom-select" name="size" required>
                            <option value="" selected>Не выбрано</option>
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                        <button class="btn btn-info btn-block my-4" name="create" type="submit">Создать проект</button>
                    </form>
                </div>
            </div>
        </div>
  </main>
  <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>

</body>
</html>