<?php $site = 'Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>
  <main class="flex-fill">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/projects">Проекты</a></li>
                        <li class="breadcrumb-item"><a href="/projects/<?php echo $project['type'].'">'.$project['type']; ?></a></li>
                        <li class="breadcrumb-item active"><?php echo $project['title']; ?></li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex card-block-1">
                            <div class="view overlay mr-3 mb-2">
                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $project['image']; ?>" alt="Card image cap">
                            </div>
                            <div>
                                <h4 class="card-title"><strong><?php echo $project['title']; ?></strong></h4>
                                <div class="row justify-content-between">
                                    <h4 class="card-title col-lg-7 col-md-9"><strong>Руководитель: <?php echo $project['curator']; ?></strong></h4>
                                    <h4 class="pr-5 pl-3" style="width: 200px;"><i class="fas fa-users" aria-hidden="true" style="padding-right: 8px;"></i><?php echo $approved_num.'/'.$project['capacity']; ?></h4>
                                </div>
                            </div>
                        </div>
                        <p class="card-text"><?php echo $project['description']; ?></p>

        <?php  if (isset($approved[0])): ?> 
            <div class="container">
                    <div class="mt-5 mb-3 d-flex justify-content-center align-items-center">
                        <h3><strong>Сформированные команды</strong></h3>
                    </div>


                        <div>

                            <h5><strong>Команда 1</strong></h5>
                            <div class="my-auto">
                                <a type="button" class="m-3 btn btn-primary btn-rounded btn-sm" href="#">Сформировать команду</a>
                            </div>

                            <?php for ($i = 0; $i < $approved_num / 2; $i++): ?>

                            <div class="card">
                                <div class="card-body">
                                    <div class="row justify-content-start">
                                        <div class="view overlay mr-3">
                                            <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $approved[$i]['pic']; ?>" alt="Card image cap">
                                        </div>
                                        <div class="my-auto">
                                            <h5><?php echo $approved[$i]['full_name']; ?></h5>
                                            <span>1 Курс, Информационные Технологии</span>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <?php endfor; ?>

                        </div>

                        <?php if ($approved_num > 1): ?>
                            <div>

                            <div class="my-3 d-flex justify-content-center align-items-center">
                                <h3><strong>Поданные заявки (Для кураторов)</strong></h3>
                            </div>

                                <?php for ($i = $approved_num / 2; $i < $approved_num; $i++): ?>

                                <div class="card">
                                    <div class="card-body">
                                        <div class="row justify-content-start">
                                            <div class="view overlay mr-3">
                                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $approved[$i]['pic']; ?>" alt="Card image cap">
                                            </div>
                                            <div class="my-auto">
                                                <h5><?php echo $approved[$i]['full_name']; ?></h5>
                                                <span>1 Курс, Информационные Технологии</span>
                                            </div>
                                            <div class="my-auto dropdown">
                                                <button class="btn btn-primary dropdown-toggle btn-sm btn-primary btn-rounded" type="button" id="dropdownMenu1" data-toggle="dropdown"
                                                aria-haspopup="true" aria-expanded="false">Добавить в команду</button>

                                                <div class="dropdown-menu dropdown-primary dropdown-user">
                                                    <a class="dropdown-item" href="#">Команда 1</a>
                                                    <a class="dropdown-item" href="#">Команда 2</a>
                                                    <a class="dropdown-item" href="#">Команда 3</a>
                                                    <a class="dropdown-item" href="#">Команда 4</a>
                                                </div>
                                            </div>
                                            <div class="my-auto">
                                                <a type="button" class="m-3 btn btn-primary btn-rounded btn-sm" href="#">Отменить заявку</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <?php endfor; ?>


                            </div>
                        <?php endif; ?>

                        <div class="my-3 d-flex justify-content-center align-items-center">
                            <h3><strong>Поданные команды (Для кураторов)</strong></h3>
                        </div>

                                <div class="card">
                                    <div class="card-body">
                                        <div class="row justify-content-start">
                                            <div class="view overlay mr-3">
                                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/temp.png" alt="Card image cap">
                                            </div>
                                            <div class="my-auto">
                                                <h5>Название команды</h5>
                                                <span>Имя Фамилия подавшего студента</span>
                                            </div>
                                            <div class="my-auto">
                                                <a type="button" class="m-3 btn btn-primary btn-rounded btn-sm" href="#">Принять команду</a>
                                            </div>
                                            <div class="my-auto">
                                                <a type="button" class="m-3 btn btn-primary btn-rounded btn-sm" href="#">Отклонить команду</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                
                <!-- <div class="table-responsive">
                    <table id="tablePreview" class="table table-striped table-sm text-nowrap">
                        <thead>
                            <tr>
                                <th><strong>Имя</strong></th>
                                <th><strong>Фамилия</strong></th>
                                <th><strong>Курс</strong></th>
                                <th><strong>Роль</strong></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="align-middle">Имя студента</td>
                                <td class="align-middle">Фамилия студента</td>
                                <td class="align-middle">Курс студента</td>
                                <td class="align-middle">Роль студента</td>
                                <td class="align-middle">
                                    <form action="" method="post">
                                        <input type="submit" class="btn btn-primary btn-rounded btn-sm" name="cancel_stud" value="Удалить студента">
                                    </form>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> -->
        <?php endif; ?>

                <?php if (isset($_SESSION['user']) && $_SESSION['user']['type'] == 'student' && !$already): ?>
                    <div class="row justify-content-center d-flex align-items-center text-center">
                        <a type="button" class="m-3 btn btn-primary btn-rounded" href="#">Подать заявку</a>
                    </div>
                    <div class="row justify-content-center d-flex align-items-center text-center">
                        <a type="button" class="m-3 btn btn-primary btn-rounded" href="/createTeam">Создать команду</a>
                    </div>
                <?php endif; ?>
                
                    </div>
                </div>
            </div>
  </main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>