<?php $site = 'Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>
  <main class="flex-fill">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="/projects">Проекты</a></li>
                        <li class="breadcrumb-item"><a href="/projects/<?php echo $project['type'].'">'.$project['type']; ?></a></li>
                        <li class="breadcrumb-item active"><?php echo $project['title']; ?></li>
                    </ol>
                </nav>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex card-block-1">
                            <div class="view overlay mr-3 mb-2">
                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $project['image']; ?>" alt="Card image cap">
                            </div>
                            <div>
                                <h4 class="card-title"><strong><?php echo $project['title']; ?></strong></h4>
                                <div class="row justify-content-between">
                                    <h4 class="card-title col-lg-7 col-md-9"><strong>Руководитель: <?php echo $project['curator']; ?></strong></h4>
                                    <h4 class="pr-5 pl-3" style="width: 150px;"><i class="fas fa-users" aria-hidden="true" style="padding-right: 8px;"></i><?php echo $approved_num.'/'.$project['capacity']; ?></h4>
                                </div>
                            </div>
                        </div>
                        <p class="card-text"><?php echo $project['description']; ?></p>

        <?php  if (isset($approved[0])): ?> 
            <div class="container">
                    <div class="mt-5 d-flex justify-content-center align-items-center">
                        <h5><strong>Сформированная команда</strong></h5>
                    </div>


                        <div class="col-md-6 col-sm-12">

                            <?php for ($i = 0; $i < $approved_num / 2; $i++): ?>

                            <div class="card">
                                <div class="card-body">
                                    <div class="d-flex">
                                                <div class="view overlay mr-3">
                                                    <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $approved[$i]['pic']; ?>" alt="Card image cap">
                                                </div>
                                                    <div class="my-auto">
                                                        <h5><?php echo $approved[$i]['full_name']; ?></h5>
                                                        <span>1 Курс, Информационные Технологии</span>
                                                    </div>
                                    </div>
                                </div>
                            </div>

                            <?php endfor; ?>

                        </div>

                        <?php if ($approved_num > 1): ?>
                            <div class="col-md-6 col-sm-12">


                                <?php for ($i = $approved_num / 2; $i < $approved_num; $i++): ?>

                                <div class="card">
                                    <div class="card-body">
                                        <div class="d-flex">
                                                    <div class="view overlay mr-3">
                                                        <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $approved[$i]['pic']; ?>" alt="Card image cap">
                                                    </div>
                                                        <div class="my-auto">
                                                            <h5><?php echo $approved[$i]['full_name']; ?></h5>
                                                            <span>1 Курс, Информационные Технологии</span>
                                                        </div>
                                        </div>
                                    </div>
                                </div>

                                <?php endfor; ?>


                            </div>
                        <?php endif; ?>


                
                
                
                
                <!-- <div class="table-responsive">
                    <table id="tablePreview" class="table table-striped table-sm text-nowrap">
                        <thead>
                            <tr>
                                <th><strong>Имя</strong></th>
                                <th><strong>Фамилия</strong></th>
                                <th><strong>Курс</strong></th>
                                <th><strong>Роль</strong></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody> -->

                            <!--Table body-->
                        <!--Table-->
                    </div>
        <?php endif; ?>

                <!-- <?php if (isset($_SESSION['user']) && $_SESSION['user']['type'] == 'student' && !$already): ?>
                    <form action="" method="post">
                        <div class="row justify-content-center d-flex align-items-center text-center">
                            <input type="text" class="form-control col-8 col-sm-4 mr-4" name="role" placeholder="Ваша роль">
                            <input type="submit" class="btn btn-primary btn-rounded" name="add" value="Подать заявку">
                        </div>
                    </form>';
                <?php endif; ?> -->

                <!-- <div class="d-flex justify-content-center align-items-center">
                    <h5><strong>Критерии проекта</strong></h5>
                </div>
                <div class="table-responsive">
                    
                    <table id="tablePreview" class="table table-striped table-sm text-nowrap">
                        
                        <thead>
                            <tr>
                                <th><strong>Код</strong></th>
                                <th><strong>Название</strong></th>
                                <th><strong>Срок</strong></th>
                                <th><strong>Процедура</strong></th>
                                <th><strong>Балл</strong></th>
                                <th><strong>Эксперты</strong></th>
                                <th><strong>Тип</strong></th>
                                <th></th>
                            </tr>
                        </thead>
                        
                        <tbody>
                        <tr>
                            <td class="align-middle">1488</td>
                            <td class="align-middle">Дизайн</td>
                            <td class="align-middle">15.05.2019</td>
                            <td class="align-middle">Субъективная</td>
                            <td class="align-middle">8</td>
                            <td class="align-middle">Эксперт1, Эксперт3, Эксперт6</td>
                            <td class="align-middle">15 дней, 50%</td>
                            <td class="align-middle">
                                <form action="" method="post">
                                    <input type="submit" class="btn btn-primary btn-rounded btn-sm" name="cancel_apr" value="Удалить критерий">
                                </form>
                            </td>
                        </tr>
                        </tbody>
                        
                    </table>
                    
                </div> -->
                
                    </div>
                </div>
            </div>
  </main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>