<?php $site = 'Мои Проекты';  include(ROOT.'/views/layouts/header.phtml'); ?>

<div class="flex-fill">
    <div class="container">
        <div class="table-wrapper-scroll-y my-custom-scrollbar">

        <table id="dtVerticalScroll" class="table table-striped table-bordered table-sm" cellspacing="0"
            width="100%">
            <thead>
                <tr>
                <th class="th-sm">Проект
                </th>
                <th class="th-sm">Куратор
                </th>
                <th class="th-sm">Тип
                </th>
                <th class="th-sm">Критерии
                </th>
                <th class="th-sm">Места
                </th>
                <th class="th-sm">Дата создания
                </th>
                <th class="th-sm">Статус
                </th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($projects as $project)
                {
                    switch($project['status']) {
                        case 0:
                            $project['status'] = 'нехватает критериев';
                            break;
                        case 1:
                            $project['status'] = 'набор студентов';
                            break;
                        case 2:
                            $project['status'] = 'в разработке';
                            break;
                        case 3:
                            $project['status'] = 'в оценивании';
                            break;
                        case 4:
                            $project['status'] = 'завершен';
                            break;
                    }
                    $cap = explode('/', $project['team/students']);
                    $cap = $cap[0]*$cap[1];
                    echo '<tr><td>'.$project['title'].'</td><td>'.$project['curator'].'</td><td>'.$project['type'].'</td><td></td><td>'.$project['mes'].'/'.$cap.'</td><td>'.$project['timeCreated'].'</td><td>'.$project['status'].'</td></tr>';
                } ?>
            </tbody>
            <tfoot>
                <tr>
                <th>Проект
                </th>
                <th>Куратор
                </th>
                <th>Тип
                </th>
                <th>Критерии
                </th>
                <th>Места
                </th>
                <th>Дата создания
                </th>
                <th>Статус
                </th>
                </tr>
            </tfoot>
            </table>

        </div>
    </div>
</div>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script src="/template/js/addons/datatables.min.js"></script>
<script>
    $(document).ready(function () {
        $('#dtVerticalScroll').DataTable({
            "scrollY": "50vh",
            "scrollCollapse": true,
        });
        $('.dataTables_length').addClass('bs-select');
    });
</script>
</body>
</html>