<?php $site = 'Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>
<link rel="stylesheet" href="/template/fullcalendar-4.2.0/packages/core/main.min.css">
<link rel="stylesheet" href="/template/fullcalendar-4.2.0/packages/daygrid/main.min.css">
<style>
.project-status {
    flex-flow: column;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: auto;
    border-radius: 2px;
}

.project-status p {
    margin-top: 2rem;
    font-size: 1.5em;
}

.input-group-addon {
    white-space: nowrap;
    vertical-align: middle;
    padding: 6px 12px;
    font-size: 16px;
    font-weight: normal;
    line-height: 1;
    color: #555555;
    text-align: center;
    background-color: #eeeeee;
    border: 1px solid #ccc;
    border-radius: 1px;
}

#calendar {
    max-width: 35rem;
}
</style>
<main class="flex-fill">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 col-md-9">
                <div class="card">
                    <div class="row">
                        <div class="col-md-2 mt-3">
                            <div class="d-flex align-self-center blue text-white project-status">
                                <p>в разработке</p>
                                <i class="fas fa-calendar-alt fa-6x"></i>
                            </div>
                            <p class="mt-1 pl-2"><?php echo $project['title']; ?></p>
                            <hr>
                            <a href="#" class="light-blue-text"><i class="pl-2 far fa-file text-black-50"></i>
                                Документ</a>
                            <hr>
                            <div class="pl-2 row">
                                <button type="button" class="btn btn-success btn-sm">Для чего та</button>
                            </div>
                        </div>
                        <div class="col-md-9 mt-3">
                            <h2 class="pl-2">Команда</h2>
                            <p class="pl-2">Сформирована <strong>10 месяцев</strong> назад</p>
                            <hr>
                            <div class="pt-2 pl-2 align-middle font-weight-light">
                                <p class="grey-text"><i class="fas fa-1x fa-users"></i> Команда</p>
                                <?php foreach($reqs as $req) {
                                    if ($req['team'] == $team)
                                    echo '<img src="/temp/'.$req['pic'].'" alt="" class="rounded-circle img-fluid pr-1"
                                    style="width: 50px">';
                                } ?>
                            </div>
                            <hr>
                            <div class="mx-auto " id="calendar"></div>
                            <hr>
                            <p class="grey-text"><i class="fas fa-1x fa-code-branch"></i> Git репозиторий</p>
                            <div class="input-group mb-3">
                                <input type="text" class="form-control"
                                    style="border-bottom-right-radius: 0; border-top-right-radius: 0;" readonly
                                    value="vogsphere@vogsphere.21-school.ru:intra/2019/activities/ft_printf/srolland">
                                <span class="input-group-addon">
                                    <i class="far fa-clone"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script src="/template/fullcalendar-4.2.0/packages/core/main.min.js"></script>
<script src="/template/fullcalendar-4.2.0/packages/daygrid/main.min.js"></script>
<script>
$(document).ready(function() {

    $(window).on('resize', function() {
        $('.project-status').height($('.project-status').width());
    }).trigger('resize');

});
document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
        plugins: ['dayGrid']
    });

    calendar.render();
});
</script>
</body>

</html>