<?php $site = 'Проект'; include(ROOT.'/views/layouts/header.phtml'); ?>
<link rel="stylesheet" href="/template/css/jquery.bootstrap.year.calendar.min.css">
<style>
.project-status {
    flex-flow: column;
    align-items: center;
    width: 220px;
    height: 220px;
    border-radius: 2px;
}

.project-status p {
    margin-top: 2rem;
    font-size: 1.5em;
}

.input-group-addon {
    white-space: nowrap;
    vertical-align: middle;
    padding: 6px 12px;
    font-size: 16px;
    font-weight: normal;
    line-height: 1;
    color: #555555;
    text-align: center;
    background-color: #eeeeee;
    border: 1px solid #ccc;
    border-radius: 1px;
}
</style>
<main class="flex-fill">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 col-md-9">
                <div class="card">
                    <div class="row">
                        <div class="col-md-2 mt-3">
                            <div class="d-flex align-self-start blue text-white project-status">
                                <p>в разработке</p>
                                <i class="fas fa-calendar-alt fa-6x"></i>
                            </div>
                            <p class="mt-1">VR energetics</p>
                            <hr>
                            <a href="#" class="light-blue-text"><i class="far fa-file text-black-50"></i> Документ</a>
                            <hr>
                            <div class="row">
                                <button type="button" class="btn btn-success btn-sm">Для чего та</button>
                            </div>
                        </div>
                        <div class="col-md-9 mt-3">
                            <h2>Команда</h2>
                            <p>Сформирована <strong>10 месяцев</strong> назад</p>
                            <hr>
                            <div class="pt-2 align-middle font-weight-light">
                                <p class="grey-text"><i class="fas fa-1x fa-users"></i> В команде 5 студентов</p>
                                <img src="/temp/temp.png" alt="" class="rounded-circle img-fluid pr-1"
                                    style="width: 50px">
                                <img src="/temp/temp.png" alt="" class="rounded-circle img-fluid pr-1"
                                    style="width: 50px">
                                <img src="/temp/temp.png" alt="" class="rounded-circle img-fluid pr-1"
                                    style="width: 50px">
                            </div>
                            <hr>
                            <div class="calendar"></div>
                            <hr>
                            <p class="grey-text"><i class="fas fa-1x fa-code-branch"></i> Git репозиторий</p>
                            <div class="input-group">
                                <input type="text" class="form-control" style="border-bottom-right-radius: 0; border-top-right-radius: 0;" readonly value="vogsphere@vogsphere.21-school.ru:intra/2019/activities/ft_printf/srolland">
                                <span class="input-group-addon">
                                    <i class="far fa-clone"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script src="/template/js/jquery.bootstrap.year.calendar.min.js"></script>
<script>
    $('.calendar').calendar();
</script>
</body>

</html>