<?php $site = 'Добавить критерий'; include(ROOT.'/views/layouts/header.phtml'); ?>

<main class="flex-fill">
    <div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title text-center mt-3"><strong>Создание критерия оценки</strong></h4>
                <form enctype="multipart/form-data" class="md-form mt-1 mb-1" action="" id="form_criteria" method="post">
                    <p class="text-left mt-3 mb-1"><strong>3. Начало проверки</strong></p>
                    <div class="row mt-3">
                        <div class="col-md-9 col-12">
                            <div class="md-form mt-0">
                                <input placeholder="Выберите дату" name="evalday" type="text" id="evalday" class="form-control datepicker" required>
                            </div>
                        </div>
                        <div id="evalday-any" class="col-md-3 col-12">
                            <div class="custom-control custom-checkbox ml-4">
                                <input type="checkbox" class="custom-control-input" id="anyDay" name="anyDay">
                                <label class="custom-control-label" for="anyDay" style="cursor: pointer;">В любой день</label>
                            </div>
                        </div>
                    </div>
                    <p class="text-left mt-3 mb-1"><strong>7. Дедлайн и штраф</strong></p>
                    <div id="deadline-row" class="row mt-3">
                        <div class="col-md-4 col-12">
                            <input placeholder="Выберите дату дедлайна" name="deadline" type="date" id="deadline" class="form-control datepicker" required disabled>
                        </div>
                    </div>
                    <button class="btn btn-info btn-block my-4" type="button" data-toggle="modal" data-target="#basicExampleModal">Добавить критерий</button>
                    <div class="modal fad" id="basicExampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLabel">Добавить критерий</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div id="modal-body" class="modal-body justify-content-center">
                                <button type="submit" class="btn btn-light-green">Готово</button>
                            </div>
                            </div>
                        </div>
                    </div>
                </form>
                <h4 class="card-title text-center mt-3"><strong>Или загрузите CSV-файл</strong></h4>
                <form class="md-form">
                    <div class="file-field">
                        <div class="btn btn-primary btn-sm float-left">
                            <span>Выбрать файл</span>
                            <input type="file" onchange="onFileSelected(event)" accept=".csv">
                        </div>
                        <div class="file-path-wrapper">
                            <input id="result" class="file-path validate" type="text" placeholder="Загрузите свой файл">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

<footer class="py-3">
    © 2019 Московский политехнический университет
</footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script>
    var crit_sum = "<?php echo $project['criteria_sum']; ?>";
</script>
<script type="text/javascript" src="/template/js/modules/material-select.js"></script>
<script type="text/javascript" src="/template/js/criteria-form.js"></script>
</body>
</html>