<?php $site = 'Кабинет'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active">Личный кабинет</li>
                </ol>
            </nav>
            <div class="row">
            <div class="card col-sm m-1">
                <div class="card-body">

                  <h4 class="card-title">Создать новый тип проекта</h4>
                  <a href="newtype" class="btn btn-primary">Создать</a>

                </div>

            </div>
            <div class="card col-sm m-1">
                <div class="card-body">

                  <h4 class="card-title">Добавить новый аккаунт</h4>
                  <a href="newacc" class="btn btn-primary">Добавить</a>

                </div>

            </div>
            <div class="card col-sm m-1">
                <div class="card-body">

                  <h4 class="card-title">Просмотр и изменение учетных записей</h4>
                  <a href="#" class="btn btn-primary">Изменить</a>

                </div>

            </div>
            </div>
        </div>
  </main>
  <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>