<?php $site = '404'; include(ROOT.'/views/layouts/header.phtml'); ?>

    <!-- 404 -->
    <h1 class="d-flex justify-content-center">404 PAGE NOT FOUND</h1>
                    <style type="text/css">
                        footer {
                        position: absolute;
                        
                        }
                    </style>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>