<?php $site = 'Проекты'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">
            <?php if (isset($category)): ?>
            <div class="card border-info">
                <div class="card-header">
                    Лидер: <?php echo $leader['surname'].' '.$leader['name'].' '.$leader['patronymic']; ?>
                </div>
                <div class="card-body">
                    <h4 class="card-title"><?php echo $leader['project_type']; ?></h4>
                    <p class="card-text"><?php echo $leader['p_type_des'] ?></p>
                    <?php if (isset($_SESSION['user']) && $_SESSION['user']['project_type'] == $leader['project_type']) echo '<a href="newtype">Редактировать</a>'; ?>
                </div>
            </div>
            <?php endif; ?>
            <?php if ($total): ?>
                <?php foreach ($projects as $project): ?>
                <?php $approved_num = Project::getApprovedTeams($project['id']); ?>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex card-block-1">
                            <div class="view overlay mr-3 mb-2">
                                <?php if ($project['image'] != 'none'): ?>
                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $project['image'] ?>" alt="Card image cap">
                                <?php else: ?>
                                <p>Нет Картинки</p>
                                <?php endif; ?>
                                <a href="/project/id-<?php echo $project['id'] ?>">
                                <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                            <div>
                                <h4 class="card-title"><strong><?php echo $project['title'] ?></strong></h4>
                                <div class="row justify-content-between">
                                    <h4 class="card-title col-lg-7 col-md-9"><strong>Руководитель: <?php echo $project['head'] ?></strong></h4>
                                    <h4 class="pr-5 pl-3" style="width: 150px;"><i class="fas fa-users" aria-hidden="true" style="padding-right: 8px;"></i><?php echo ($approved_num.'/'.$project['capacity']) ?></h4>
                                </div>
                            </div>
                        </div>
                        <p class="card-text"><?php echo $project['description'] ?></p>
                        <hr>
                        <div class="d-flex justify-content-center align-items-center">
                            <a href="/project/id-<?php echo $project['id'] ?>" class="text-primary">

                                <!-- (Для лидера) Сделать так чтобы только на проектах с тем же направлением что и у лидера высвечивалась кнопка редактировать. -->
                                <?php if(isset($_SESSION['user']) && $_SESSION['user']['project_type'] == $project['fac']): ?>
                                    <h4 class="waves-effect waves-light"><strong>Редактировать</strong></h4>
                                <?php elseif(isset($_SESSION['user']) && $_SESSION['user']['type'] == 'student'): ?>
                                    <h4 class="waves-effect waves-light"><strong>Записаться</strong></h4>
                                <?php else: ?>
                                    <h4 class="waves-effect waves-light"><strong>Просмотреть</strong></h4>
                                <?php endif; ?>
                            </a>
                        </div>
                    </div>
                </div>


                <?php endforeach; ?>
                
                <?php if ($total > 3) echo $pagination->get(); ?>
            <?php else: ?>
                <h1 class="d-flex justify-content-center">Не найдены проекты</h1>
            <?php endif; ?>
        </div>
        <?php if(isset($_SESSION['user']) && $_SESSION['user']['type'] == 'leader'): ?>
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                    <a class="btn-floating btn-lg blue-gradient" href="/profile/addproject"><i class="fas fa-plus"></i></a>
            </div>
        <?php endif;?>
  </main>
    <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>