<?php $site = 'Проекты'; include(ROOT.'/views/layouts/header.phtml'); ?>

  <main class="flex-fill">
        <div class="container">

            <div class="card border-info">
                <div class="card-header">
                    Лидер: Даньшина Марина Владимировна
                </div>
                <div class="card-body">
                    <h4 class="card-title">Дизайн</h4>
                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <a href="#">Редактировать</a>
                </div>
            </div>

            <?php if ($total): ?>
                <?php foreach ($projects as $project): ?>
                <?php $approved_num = Project::getApprovedTeams($project['id']); ?>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex card-block-1">
                            <div class="view overlay mr-3 mb-2">
                                <?php if ($project['image'] != 'none'): ?>
                                <img class="card-img-top" style="border-radius: 50%; width: 80px; height: 80px;" src="/temp/<?php echo $project['image'] ?>" alt="Card image cap">
                                <?php else: ?>
                                <p>Нет Картинки</p>
                                <?php endif; ?>
                                <a href="/project/id-<?php echo $project['id'] ?>">
                                <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                            <div>
                                <h4 class="card-title"><strong><?php echo $project['title'] ?></strong></h4>
                                <div class="row justify-content-between">
                                    <h4 class="card-title col-lg-7 col-md-9"><strong>Руководитель: <?php echo $project['head'] ?></strong></h4>
                                    <h4 class="pr-5 pl-3" style="width: 150px;"><i class="fas fa-users" aria-hidden="true" style="padding-right: 8px;"></i><?php echo ($approved_num.'/'.$project['capacity']) ?></h4>
                                </div>
                            </div>
                        </div>
                        <p class="card-text"><?php echo $project['description'] ?></p>
                        <hr>
                        <!-- Button -->
                        <div class="d-flex justify-content-center align-items-center">
                            <a href="/project/id-<?php echo $project['id'] ?>" class="text-primary">
                                <h4 class="waves-effect waves-light"><strong>Записаться</strong></h4>
                            </a>
                        </div>
                    </div>
                </div>


                <?php endforeach; ?>
                
                <?php if ($total > 3) echo $pagination->get(); ?>
            <?php else: ?>
                <h1 class="d-flex justify-content-center">Не найдены проекты</h1>
            <?php endif; ?>
        </div>
        <?php if(isset($_SESSION['user']) && $_SESSION['user']['type'] == 'leader'): ?>
            <div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
                    <a class="btn-floating btn-lg blue-gradient" href="/profile/addproject"><i class="fas fa-plus"></i></a>
            </div>
        <?php endif;?>
  </main>
    <footer class="py-3">
    © 2019 Московский политехнический университет
  </footer>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>