<div class="mt-5 mb-3 d-flex justify-content-center align-items-center">
                        <h3><strong>Репозитории</strong></h3>
                    </div>

                    <div class="row justify-content-start my-3">
                        <h5 class="my-auto mx-3 mb-2"><strong>Требования</strong></h5>
                        <a href="#">Добавить файл</a>
                        <div class="w-100"></div>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Доки.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Требования.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл 4</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл.pdf</a>
                    </div>

                    <div class="row justify-content-start my-3">
                        <h5 class="my-auto mx-3 mb-2"><strong>Команды</strong></h5>
                        <a href="#">Добавить файл</a>
                        <div class="w-100"></div>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Доки.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Требования.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл 4</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл.pdf</a>
                    </div>

                    <div class="row justify-content-start my-3">
                        <h5 class="my-auto mx-3"><strong>Итог</strong></h5>
                        <a href="#">Добавить файл</a>
                        <div class="w-100"></div>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Доки.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Требования.txt</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл 4</a>
                        <a type="button" href="#" class="col-md-auto btn btn-deep-purple">Файл.pdf</a>
                    </div>

                                        <!-- Для студента -->
                                        <div class="row justify-content-center d-flex align-items-center text-center">
                        <a type="button" class="m-3 btn btn-primary btn-rounded" href="#">Покинуть команду</a>
                    </div>

                    <div class="d-flex justify-content-center align-items-center">
                        <h3><strong>Критерии проекта</strong></h3>
                    </div>

                    <!-- Для куратора -->
                    <div class="row justify-content-center d-flex align-items-center text-center">
                        <a type="button" class="m-3 btn btn-primary btn-rounded" href="createCriteria">Создать
                            критерий</a>
                    </div>

                    <!-- Для куратора -->
                    <h5 class="m-3 row"><strong>Выставленные критерии</strong></h5>
                    <div class="table-responsive">
                        <table id="tablePreview" class="table table-striped table-sm text-nowrap">
                            <thead>
                                <tr>
                                    <th><strong>Код</strong></th>
                                    <th><strong>Название</strong></th>
                                    <th><strong>Срок</strong></th>
                                    <th><strong>Процедура</strong></th>
                                    <th><strong>Балл</strong></th>
                                    <th><strong>Эксперт</strong></th>
                                    <th><strong>Тип</strong></th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr>
                                    <td class="align-middle">1488</td>
                                    <td class="align-middle">Дизайн</td>
                                    <td class="align-middle">15.05.2019</td>
                                    <td class="align-middle">Субъективная</td>
                                    <td class="align-middle">8</td>
                                    <td class="align-middle"> Эксперт3</td>
                                    <td class="align-middle">15 дней, 50%</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                                        <!-- Для эксперта -->
                                        <h5 class="m-3 row"><strong>Критерии для оценки</strong></h5>
                    <div class="table-responsive">
                        <table id="tablePreview" class="table table-striped table-sm text-nowrap">
                            <thead>
                                <tr>
                                    <th><strong>Код</strong></th>
                                    <th><strong>Название критерия</strong></th>
                                    <th><strong>Срок</strong></th>
                                    <th><strong>Процедура</strong></th>
                                    <th><strong>Тип</strong></th>
                                    <th></th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr>
                                    <td class="align-middle">1488</td>
                                    <td class="align-middle">Дизайн</td>
                                    <td class="align-middle">15.05.2019</td>
                                    <td class="align-middle">Субъективная</td>
                                    <td class="align-middle">15 дней, 50%</td>
                                    <td class="align-middle">
                                        <form action="" method="post">
                                            <input type="submit" class="m-2 btn btn-primary btn-rounded btn-sm"
                                                name="cancel_apr" value="Оценить критерий">
                                        </form>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>