<?php $site = 'Добавить критерий'; include(ROOT.'/views/layouts/header.phtml'); ?>

<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <div class="card">
                    <div class="list-group">
                        <a href="/teammaking-id<?php echo $id; ?>" class="list-group-item list-group-item-action ">
                            Заявки и команды
                        </a>
                        <a href="/addCriteria-id<?php echo $id; ?>"
                            class="list-group-item list-group-item-action active">Критерии</a>
                    </div>
                    <?php if ($setup == 1): ?>
                    <div class="text-center">
                        <button type="button" class="btn btn-success" data-toggle="modal"
                            data-target="#basicExampleModal">
                            Разработка
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        После этого действия проект передет в стадию разработки!
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Назад</button>
                                        <form action="" method="post">
                                            <button name="welcome" type="submit" class="btn btn-primary">Подтвердить</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-md-10">
                <h3 class="text-center"><strong>Критерии</strong></h3>
                <div class="w-100"></div>
                <div class="table-wrapper-scroll-y table-wrapper-scroll-x request-table-wrapper ">
                    <table id="request-table" class="table">
                        <thead>
                            <tr>
                                <th class="th-sm">Код
                                </th>
                                <th class="th-sm">Название
                                </th>
                                <th class="th-sm">От - До
                                </th>
                                <th class="th-sm">Процедура
                                </th>
                                <th class="th-sm">Баллы
                                </th>
                                <th class="th-sm">Эксперт
                                </th>
                                <th class="th-sm">Штраф в процентах
                                </th>
                        </thead>
                        <tbody>
                        <?php foreach($criterias as $cr)
                        {
                            echo '<tr class="align-items-center"><td>'.$cr['code'].'</td><td>'.$cr['name'].'</td><td>'.$cr['evalday'].' - '.$cr['deadline'].'</td><td>';
                            if ($cr['produ'] == 'on')
                                echo 'Субъективная';
                            else
                                echo 'Объективная';
                            echo '</td><td> '.$cr['points'];
                            if ($cr['points'] % 10 == 1)
                                echo ' балл';
                            else
                                echo ' баллов';
                            echo '</td><td>'.$cr['exsurname'].' '.$cr['exname'].' '.$cr['expatronymic'].' <img class="card-img-top rounded-circle" style="width: 40px; height: 40px;" src="/temp/'.$cr['pic'].'" alt="Card image cap"></td><td>'.$cr['penalty'].'%</td>';
                        } ?>
                        </tbody>
                    </table>
                </div>
                <?php if ($project['criteria_sum'] < 100): ?>
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title text-center mt-3"><strong>Создание критерия оценки</strong></h4>
                        <form enctype="multipart/form-data" class="md-form mt-1 mb-1" action="" id="form_criteria"
                            method="post">
                            <p class="text-left mt-3 mb-1"><strong>1. Код</strong></p>
                            <div class="md-form mt-3">
                                <input type="text" id="code" name="code" class="form-control" pattern="[0-9]+" required>
                                <label for="code">Код</label>
                            </div>
                            <p class="text-left mt-3 mb-1"><strong>2. Наименование</strong></p>
                            <div class="md-form mt-3">
                                <input type="text" id="name" name="name" class="form-control" required>
                                <label for="name">Наименование</label>
                            </div>
                            <p class="text-left mt-3 mb-1"><strong>3. Начало проверки</strong></p>
                            <div class="row mt-3">
                                <div class="col-md-9 col-12">
                                    <div class="md-form mt-0">
                                        <input placeholder="Выберите дату" name="evalday" type="text" id="evalday"
                                            class="form-control datepicker" required>
                                    </div>
                                </div>
                                <div id="evalday-any" class="col-md-3 col-12">
                                    <div class="custom-control custom-checkbox ml-4">
                                        <input type="checkbox" class="custom-control-input" id="anyDay" name="anyDay">
                                        <label class="custom-control-label" for="anyDay" style="cursor: pointer;">В
                                            любой
                                            день</label>
                                    </div>
                                </div>
                            </div>
                            <p class="text-left mt-3 mb-0"><strong>4. Процедура</strong></p>
                            <div class="custom-control custom-radio ml-4">
                                <input type="radio" class="form-check-input" id="defaultInline1" name="procedure"
                                    checked>
                                <label class="custom-control-label" for="defaultInline1"
                                    style="cursor: pointer;">Субъективный</label>
                            </div>
                            <div class="custom-control custom-radio ml-4">
                                <input type="radio" class="form-check-input" id="defaultInline2" name="procedure">
                                <label class="custom-control-label" for="defaultInline2"
                                    style="cursor: pointer;">Объективный</label>
                            </div>
                            <p class="text-left mt-3 mb-1"><strong>5. Балл</strong></p>
                            <select class="mdb-select md-form" name="points" id="points" required>
                                <option value="" disabled selected>Выберите балл</option>
                                <?php
							for ($i = 1; ($i <= 10 && $i + $project['criteria_sum'] <= 100); $i++)
								echo '<option value="'.$i.'">'.$i.'</option>';
							?>
                            </select>
                            <p class="text-left mt-3 mb-1"><strong>6. Эксперты</strong></p>
                            <select class="mdb-select md-form" name="expert" searchable="Введите имя..." required>
                                <option value="" disabled selected>Выберите эксперта</option>
                                <?php foreach($experts as $expert) {
                            echo '<option value="'.$expert['id'].'" data-icon="/temp/'.$expert['pic'].'" class="rounded-circle">'.$expert['surname'].' '.$expert['name'].' '.$expert['patronymic'].'</option>';
                        } ?>
                            </select>
                            <p class="text-left mt-3 mb-1"><strong>7. Дедлайн и штраф</strong></p>
                            <div id="deadline-row" class="row mt-3">
                                <div class="col-md-4 col-12">
                                    <input placeholder="Выберите дату дедлайна" name="deadline" type="text"
                                        id="deadline" class="form-control datepicker" required disabled>
                                </div>
                                <div class="col-md-4 col-12">
                                    <select class="mdb-select md-form" id="penalty" name="penalty" required>
                                        <option value="" disabled selected>Штраф в процентах</option>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                        <option value="9">9</option>
                                        <option value="10">10</option>
                                    </select>
                                </div>
                            </div>
                            <button class="btn btn-info btn-block my-4" type="submit">Добавить критерий</button>
                        </form>
                        <h4 class="card-title text-center mt-3"><strong>Или загрузите CSV-файл</strong></h4>
                        <form class="md-form">
                            <div class="file-field">
                                <div class="btn btn-primary btn-sm float-left">
                                    <span>Выбрать файл</span>
                                    <input type="file" onchange="onFileSelected(event)" accept=".csv">
                                </div>
                                <div class="file-path-wrapper">
                                    <input id="result" class="file-path validate" type="text"
                                        placeholder="Загрузите свой файл">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <?php endif; ?>
            </div>
        </div>
    </div>
</main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script>
var crit_sum = "<?php echo $project['criteria_sum']; ?>";
</script>
<script type="text/javascript" src="/template/js/modules/material-select.js"></script>
<script type="text/javascript" src="/template/js/criteria-form.js"></script>
</body>

</html>