<?php $site = 'Команды'; include(ROOT.'/views/layouts/header.phtml'); ?>

<main>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <div class="card">
                    <div class="list-group">
                        <a href="/teammaking-id<?php echo $id; ?>"
                            class="list-group-item list-group-item-action active">
                            Заявки и команды
                        </a>
                        <a href="/addCriteria-id<?php echo $id; ?>"
                            class="list-group-item list-group-item-action">Критерии</a>
                    </div>
                    <?php if ($setup == 1): ?>
                    <div class="text-center">
                        <button type="button" class="btn btn-success" data-toggle="modal"
                            data-target="#basicExampleModal">
                            Разработка
                        </button>

                        <!-- Modal -->
                        <div class="modal fade" id="basicExampleModal" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Вы уверены?</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        После этого действия проект передет в стадию разработки!
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Назад</button>
                                        <form action="" method="post">
                                            <button name="welcome" type="submit" class="btn btn-primary">Подтвердить</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>
                </div>
            </div>
            <div class="col-md-10">
                <div class="card container-fluid">
                    <h3 class="text-center"><strong>Участники без команд</strong></h3>
                    <div class="w-100"></div>
                    <div class="table-wrapper-scroll-y table-wrapper-scroll-x request-table-wrapper ">
                        <table id="request-table" class="table">
                            <thead>
                                <tr>
                                    <th class="th-sm">Аватар
                                    </th>
                                    <th class="th-sm">Ф.И.О
                                    </th>
                                    <th class="th-sm">Кто и откуда
                                    </th>
                                    <th></th>
                                    <th></th>
                            </thead>
                            <tbody>
                                <?php foreach($reqs as $req): ?>
                                <?php if ($req['app'] == 0): ?>
                                <tr class="align-items-center">
                                    <td><img class="card-img-top rounded-circle" style="width: 50px; height: 50px;"
                                            src="/temp/<?php echo $req['pic']; ?>" alt="Card image cap"></td>
                                    <td><?php echo $req['surname'].' '.$req['name'].' '.$req['patronymic']; ?></td>
                                    <td><?php echo $req['position']; ?></td>
                                    <?php if ($no == 0): ?>
                                    <td>
                                        <form id="user<?php echo $req['id']; ?>" method="post">
                                            <select name="team" class="mdb-select md-form" required>
                                                <option value="" disabled selected>Выбрать команду</option>
                                                <?php for ($i = 1; $i <= $teams; $i++) {
                                                    if ($shit[$i - 1] < $cap)
                                                        echo '<option value="'.$i.'">Команда '.$i.'</option>';
                                                }
                                            ?>
                                            </select>
                                        </form>
                                    </td>
                                    <td>
                                        <button form="user<?php echo $req['id']; ?>" type="submit" name="addToTeam"
                                            class="m-2 btn btn-primary btn-rounded btn-sm"
                                            value="<?php echo $req['id']; ?>">Добавить в команду</button>
                                    </td>
                                    <?php endif; ?>
                                </tr>
                                <?php endif; ?>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <?php for ($i = 1; $i <= $teams; $i++): ?>
                    <div class="card border-dark border-round p-0 m-3 col-sm">
                        <div class="card-header">Команда <?php echo $i; ?></div>
                        <div class="card-body px-5">
                            <?php foreach($reqs as $req): ?>
                            <?php if ($req['app'] == 1 && $req['team'] == $i): ?>
                            <div class="row justify-content-start">
                                <div class="view overlay mr-3">
                                    <img class="card-img-top rounded-circle" style="width: 40px; height: 40px;"
                                        src="/temp/<?php echo $req['pic']; ?>" alt="Card image cap">
                                </div>
                                <div class="my-auto">
                                    <h5><?php echo $req['surname'].' '.$req['name'].' '.$req['patronymic']; ?></h5>
                                    <span><?php echo $req['position'] ?></span>
                                </div>
                                <form method="post">
                                    <button type="submit" class="m-3 btn btn-primary btn-rounded btn-sm" name="delDom"
                                        value="<?php echo $req['id']; ?>">Выгнать из Дома 2</button>
                                </form>
                            </div>
                            <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                    </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

<?php include(ROOT.'/views/layouts/footer.phtml'); ?>
<script src="/template/js/addons/datatables.min.js"></script>
<script>
$(document).ready(function() {
    $('#request-table').DataTable({
        "scrollY": "50vh",
        "scrollX": true,
        "scrollCollapse": true,
    });
    $('.mdb-select').materialSelect();
    $('.dataTables_length').addClass('bs-select');
});
</script>
</body>

</html>